stages:
- name: compile
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm build
- name: release
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: q7w_front
      registry: 127.0.0.1:34137
- name: pag
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: "1"
    notifier: c-96h8h:n-ng2lv
  condition:
  - Success
  - Changed
  - Failed
